version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf

python:
  version: 3.10
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"