version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - epub
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .

